---
version: '3'

tasks:
  default:
    cmds:
      - task: test
      - task: build

  build:
    desc: Build the project
    cmds:
      - go build -o {{cookiecutter.app_name}} main.go

  run:
    desc: Run the project
    cmds:
      - go run main.go

  test:
    desc: Run tests
    cmds:
      - go test -v ./...
